apiVersion: v1
kind: Pod
metadata:
  name: insecure-pod
spec:
  hostNetwork: true   # ❌ security issue
  containers:
    - name: nginx
      image: nginx:latest
      securityContext:
        privileged: true   # ❌ critical issue
